title: Sex and the City San Fransisco edititon
description: and the raise of the internet
sitename: Crime data
baseurl: 'https://cats-and-the-city.github.io/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
