title: Cat's & the city 
description:
sitename: Cat's & the city
baseurl: 'https://cats-and-the-city.github.io/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
